Lesson6
KUlanov/TestGuru pull request #8
Opened 2023-09-08 15:59 UTC by KUlanov

2023-09-08 18:26 UTC, BubuntuClu requested changes

2023-09-08 18:26 UTC, BubuntuClu commented on app/models/answer.rb
> +    errors.add(:answers_count) unless (0..4).include?(question.answers.count)
нижнюю границу не надо здавать. только врехнюю стоит проверять

2023-09-08 18:26 UTC, BubuntuClu commented on app/models/question.rb
> +  scope :correct_answers, -> {answers.where(correct: true) }
это в модели ответов должно быть

2023-09-08 18:26 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :test_of_category, -> (category_name) {Category.find_by(title: category_name).tests.order(title: :DESC)}
1 - перепиши запрос через join
2 - сортировку и выборку не надо помещать в скоуп.
скоуп должен возвращать объект ActiveRecord::Relation, pluck возвращает массив.
так же скоуп это универсальный метод, который может использован в разных частях приложения, там может потребоваться другая сортировка и выборка.
метод надо оставить, заменить часть выражения на скоуп и уже к скоупу применить сортировку и выборку

2023-09-08 18:26 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :name, presence: true,
зачем имя ограничивать уникальностью?

2023-09-08 18:26 UTC, BubuntuClu commented on db/migrate/20230908153910_index_test_on_title_and_level.rb
> +    add_index(:tests, [:title, :level], unique: true)
нужно еще в модели написать ограничение по этой паре моделей.

2023-09-09 06:16 UTC, KUlanov commented on app/models/answer.rb
> +    errors.add(:answers_count) unless (0..4).include?(question.answers.count)
Переписал, но в ТЗ указано от 1-го до 4-х

2023-09-09 06:38 UTC, KUlanov commented on app/models/user.rb
> +  validates :name, presence: true,
Ну у нас пока нет определенного поля по которому мы идентефицируем пользователей. Решил что пока будет имя.

2023-09-09 18:04 UTC, BubuntuClu commented on app/models/answer.rb
> +    errors.add(:answers_count) unless question.answers.count <5
`unless` сложнее для восприятия. переделай через `if`

2023-09-09 18:05 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :name, presence: true,
у тебя ведь есть email, который точно должен буть уникальный. по нему и можно идентифицировать пользователей. в реальности ведь фио может совпадать, а вот дублирующие почты нет

2023-09-12 14:04 UTC, merged